"""add views cover_image deleted_at post_logs

Revision ID: c3302f0d02c3
Revises: e78bfa37a2d1
Create Date: 2026-05-12 20:45:09.547512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3302f0d02c3'
down_revision: Union[str, None] = 'e78bfa37a2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('operated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_logs_id'), 'post_logs', ['id'], unique=False)
    op.add_column('posts', sa.Column('cover_image', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'deleted_at')
    op.drop_column('posts', 'views')
    op.drop_column('posts', 'cover_image')
    op.drop_index(op.f('ix_post_logs_id'), table_name='post_logs')
    op.drop_table('post_logs')
    # ### end Alembic commands ###
